# Generated by Django 5.2.7 on 2025-10-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myphoto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='geo_coded_at',
            field=models.DateTimeField(blank=True, help_text='When geocoding was last performed for this photo', null=True),
        ),
    ]
