# Generated by Django 5.2.7 on 2025-12-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myphoto', '0002_add_geo_coded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_location_manual',
            field=models.BooleanField(default=False, help_text='Whether location was manually set/updated by user'),
        ),
    ]
