# Generated by Django 5.2.7 on 2025-12-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myphoto', '0003_photo_is_location_manual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='h3_res_12',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='h3_res_15',
        ),
        migrations.AddField(
            model_name='photo',
            name='h3_res_10',
            field=models.CharField(blank=True, db_index=True, help_text='H3 resolution 10 (~15,000 m²) - sub-neighborhood level', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='h3_res_11',
            field=models.CharField(blank=True, db_index=True, help_text='H3 resolution 11 (~2,150 m²) - street/block level', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='h3_res_3',
            field=models.CharField(blank=True, db_index=True, help_text='H3 resolution 3 (~12,400 km²) - multi-state region level', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='h3_res_6',
            field=models.CharField(blank=True, db_index=True, help_text='H3 resolution 6 (~36 km²) - metropolitan area level', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='h3_res_9',
            field=models.CharField(blank=True, db_index=True, help_text='H3 resolution 9 (~105,000 m²) - neighborhood level', max_length=15, null=True),
        ),
    ]
